### ISSUE TITLE
python client

### ISSUE THREAD

**Issue by soumith** [TorchCraft/TorchCraft#1]
this issue will invariably be opened by someone within the next few 10s of hours, so might as well open it and give folks some pointers.

To have a working and minimal python client (that does [baseline_heuristics](https://github.com/TorchCraft/TorchCraft/blob/master/examples/baseline_heuristics.lua)), you need to do three main things:
1. transpile init.lua to init.py: https://github.com/TorchCraft/TorchCraft/blob/master/init.lua . The work is mostly mechanical / codemod, and most of the static constants are planned to eventually move to C++ anyways. 
2. Add python / cython bindings for replayer.frameFromString, which ends up being this set of code: 
    1. https://github.com/TorchCraft/TorchCraft/blob/7a3f2f5f248cbfc01d2593b67df831bc98542677/replayer/frame_lua.cpp#L52-L54
    2. https://github.com/TorchCraft/TorchCraft/blob/master/replayer/frame.cpp#L116
3. Add conditional compilation to the lua bits of replayer controlled by an #ifdef. Actually, one has to verify, but you might just get away with only compiling frame.cpp and nothing else for frameFromString functionality.

That should be sufficient to get one going.

Looking forward to the PRs: 

cc: @sherjilozair who asked about it

**Comment by tangzk** [comment]
It this a way to execute python script from lua environment?

**Comment by CDLuminate** [comment]
[off-topic]  
Such work is super awesome, since the programmer need to play video game to test the model before submitting the paper.

**Comment by ebetica** [comment]
@tangzk try https://github.com/facebook/fblualib/blob/master/fblualib/python

I think you can install this with `luarocks install python`

**Comment by liboyue** [comment]
[off-topic-again]
In https://github.com/TorchCraft/TorchCraft/blob/master/docs/user/bwapi_on_linux.md , the clone command should be "git clone https://github.com/TorchCraft/TorchCraft.git"...

**Comment by tangzk** [comment]
Hi, guys, we have built a python client for torchcraft([https://github.com/deepcraft/torchcraft-py](https://github.com/deepcraft/torchcraft-py)), and a gym-compatible environment based on this([https://github.com/deepcraft/gym-starcraft](https://github.com/deepcraft/gym-starcraft)). You can try Starcraft AI agent on tensorflow/keras/rllab by using these.
Any suggestions will be appreciated.
