### ISSUE TITLE
game mapping table not found

### ISSUE THREAD

**Issue by xwzy** [TorchCraft/TorchCraft#11]
When I launch the exe and run the sample code in client, the server machine keeps outputing mapping table not found in cmd. I use windows 7 in virtual machine on my mac, how to solve that?

**Comment by nanxintin** [comment]
Hi @xwzy, I came across the same error when running  "th simple_exe.lua -t $server_ip".
I installed the SC and BWAPI in the Win10 and torchcraft in Ubuntu16.04 of a virtual machine.
How did you solved the error at last?
Thanks.

**Comment by edran** [comment]
@nanxintin BWAPI currently doesn't support Win10.

**Comment by nanxintin** [comment]
@edran Thank you for your reply.
I tried to installed the SC and BWAPI in a Win7 virtual machine, but the same problem still occurred.
This time I run the torchcraft example "th simple_exe.lua -t $server_ip" on my mac.

**Comment by nanxintin** [comment]
Hi @xwzy , can you give me some advice to solve the error? It has troubled me for a few days.
