### ISSUE TITLE
Python client crashes after launching

### ISSUE THREAD

**Issue by yiyang92** [TorchCraft/TorchCraft#120]
Bwapi log:

//////////////////////////////////////////////////
TIME: Mon Apr 17 17:32:10 2017

VERSION: 1.16.1.1
BWAPI:
  REVISION: 4708
  BUILD: RELEASE
  ERROR: None
  LOCATION: Single Player 
MAP: 4_dragoons_2_ultralisks
     3mar1zeal.scm

EXCEPTION: 0xC0000005    EXCEPTION_ACCESS_VIOLATION
FAULT:     0x69F74F78    czmq.dll
REGISTERS:
  EDI: 0494E048
  ESI: 00000000
  EBX: 00000000
  EDX: 00000000
  ECX: 00000000
  EAX: 00000000
  EBP: 0019F928
  EIP: 69F74F78
  ESP: 0019F928
STACK:
  czmq.dll          0x69F74F78    zsock_is
  czmq.dll          0x69F755D0    zsock_resolve
  czmq.dll          0x69F719E6    zmsg_send
  czmq.dll          0x69F7643E    zsock_vsend
  czmq.dll          0x69F75642    zsock_send
  BWEnv.dll         0x68FB6713    newAIModule
  BWEnv.dll         0x68FA32F0      ----
  BWEnv.dll         0x68FA8A48    newAIModule
  BWAPI.dll         0x1003471E      ----
  BWAPI.dll         0x1003496A      ----
  BWAPI.dll         0x10041BC9      ----
  BWAPI.dll         0x100345E7      ----

**Comment by spencerduncan** [comment]
I'm guessing you're using the release BWEnv.dll with the develop branch of TorchCraft, which usually doesn't work. If that's the case, you'll need to compile a new copy of BWEnv.dll or wait for python support to be merged into master.

**Comment by spencerduncan** [comment]
@yiyang92 I've had success using the python client with OpenBW. I haven't tried with the standard BWAPI.

**Comment by edran** [comment]
Closing because most likely answered by @spencerduncan :)
