### ISSUE TITLE
Static Map Data for Pathfinding

### ISSUE THREAD

**Issue by spencerduncan** [TorchCraft/TorchCraft#14]
> If someone wants to make an agent for path finding, or to actually play a full game, they'll need the map elevation and pathing data. Anyone who's tried to make Dragoons walk down a ramp knows that dealing with Brood War unit pathing can a complex task. There are a few BWAPI functions that can be used to get the necessary data:
> 
> - `int getGroundHeight(int tileX, int tileY) const`
>     -Returns an integer corresponding to the elevation at the queried tile (32x32)
> - `bool isWalkable(int walkX, int walkY) const`
>     -Returns true if the corresponding walk tile (8x8) is walkable. Does not account for any structures or units on the tile.
> - `Unitset& getStaticNeutralUnits() const`
>     -Returns a list of all Neutral Units (critters, minerals, geysers, neutral structures) available at the beginning of the game. Similar functions exist for just minerals and just geysers.
> 
> None of these functions require vision or for the map hack to be enabled. BWAPI considers pre-game knowledge of the map layout to be reasonable as most players would study a given prior to playing on it.
> 
> My thought is that these functions could be called once at the beginning of the game to get the necessary data from the C++ side to the Torch side to be used as necessary. If the extra processing time at the beginning of the game is an issue for repeated trials these values could be saved to disk and retrieved using `mapHash()` to identify the map. It could also be setup such that this function is skipped on micro_games.
> 
> While the above functions should be sufficient for pathfinding purposes, this would also be a good point to include `isBuildable()` as well, as someone will want that eventually.
> 
> BWAPI does not seem to include any methods for identifying ramps, however a learning agent should be able to infer there existence from the correlations between `getGroundHeight` and `isWalkable` data.

After writing all that I see that [mapToTensor](https://github.com/TorchCraft/TorchCraft/blob/7a3f2f5f248cbfc01d2593b67df831bc98542677/BWEnv/src/utils.cc#L181) already exists, and is already sending data to lua, which doesn't get used anywhere. I'm going to keep all the stuff I wrote above in case someone wants to repurpose it for documentation.

Right now it only has `getGroundHeight`, `isWalkable` and a comment for `isBuildable`. The data for this appears to be stored as a 2D `ByteTensor` with values corresponding to `getGroundHeight`, unless the mini-tile is non walkable, in which case the value is set to -1 (technically 255 because `ByteTensor` is unsigned). Since this is only called once in `setupHandshake`, it would be good to send all usable initial map data ( `getGroundHeight`,  `isWalkable`,  `isBuildable`, `getStaticNeutralUnits`, `getStartLocations`) in this function. I also think that separating `getGroundHeight` and `isWalkable` could be beneficial, as there are a few cases where combining them doesn't give the whole picture. For example, where there's a 1 tile large non-walkable elevation where someone could hide an Overlord that's invisible from low ground vs a one tile large non-walkable water doodad.

The simplest way to implement this would be as a 3D (X,Y,5) `ByteTensor` where each of the 5 values in the third dim hold the different attributes. The issue is that this would generate a up to a 5MB (`(255 tiles x 4 walk tiles)^2*5`) tensor, most of which is created because of the resolution of `isWalkable`. `getStartLocations` in particular would be very sparse, and is perhaps better suited to be a separate variable. Perhaps this is a non-issue. This is only written once per game and can be processed afterwards to suit whatever computation needs to be preformed. Other solutions would include hashing the different combinations into a 2D `ByteTensor`, separating the fields into different Tensors such that `isWalkable` has an 8 pixel resolution, `getGroundHeight` and `isBuildable` have 32 pixel resolution, and that `getStaticNeutralUnits` and `getStartLocations` are lists, or some combination of the two. Some sort of autoencoder may also be applicable, but I don't know if the actual machine learning bits are within this scope of this project.

To go with those changes, some kind of accessor functions should probably written on the lua side since `map_data` would no longer be a simple tensor. Some sort of layer function similar to the ones that currently exist for visibility and unit stats would probably be useful as well.

I'm willing to work on any of this, but I thought I would actually submit an issue for discussion first instead of jumping straight to a pull request again.

**Comment by ebetica** [comment]
This is implemented in https://github.com/TorchCraft/TorchCraft/pull/102

The neutral units are packed, so you can simply query the units field for them.
