### ISSUE TITLE
Installation issue on latest version

### ISSUE THREAD

**Issue by tegg89** [TorchCraft/TorchCraft#149]
I am installing TorchCraft in Ubuntu. However, I think currently it does not work due to the latest version. I think the all versions of dependencies are wrong following by StarCraft version 1.18.

Here is my details of environment and dependencies and installation processes:

OS: Ubuntu 16.04
Wine: wine2.9 (Staging)
 - When I installed Starcraft via original Wine, the different version of Starcraft has caused error (plus free version, no requiring license key anymore).
- So I installed `winehq-staging` instead and checked out Starcraft could run properly!

(Then installed `winetricks -q vcrun2013`)

BWAPI: 4.2.0
- Previous version BWAPI_412 got crashes with wine. So I searched the latest version of it and installed.

(Then I successfully installed TorchCraft with `quick_setup.sh`)

Then I ran common prerequisites.
> Copy $STARCRAFT/TorchCraft/config/bwapi.ini in $STARCRAFT/bwapi-data/bwapi.ini.
> Copy $STARCRAFT/TorchCraft/config/torchcraft.ini in $STARCRAFT/bwapi-data/torchcraft.ini.
> Copy $STARCRAFT/TorchCraft/BWEnv/bin/*.dll into $STARCRAFT/.
> Copy $STARCRAFT/TorchCraft/maps/* into $STARCRAFT/Maps/BroodWar.

While following [BWAPI on Linux](https://github.com/TorchCraft/TorchCraft/blob/master/docs/user/bwapi_on_linux.md), I got another error in running AIModule.
`wine bwheadless.exe -e $STARCRAFT/StarCraft.exe -l $STARCRAFT/bwapi-data/BWAPI.dll --headful` and "Game Initialization Failed!" message box came out.

**Comment by edran** [comment]
BWAPI unfortunately does not support 1.18, hence we can't support it either. We are soon going to document a way to get around this, however for now I suggest using 1.16.
