### ISSUE TITLE
tc:is_building does not recognize Terran_Command_Center

### ISSUE THREAD

**Issue by enguyen-ca** [TorchCraft/TorchCraft#15]
Looks like tc:is_building doesn't work on Terran Command Center.

**Comment by spencerduncan** [comment]
I see the issue. `is_building` checks for the type id to be between `Terran_Comsat_Station` and `Protoss_Shield_Battery`, and `Terran_Command_Center` is one less than `Terran_Comsat_Station`. I'll submit a fix.

**Comment by ebetica** [comment]
Thanks! I merged your pull https://github.com/TorchCraft/TorchCraft/pull/16
