### ISSUE TITLE
StarCraft latest free version installation issue on different VMware platform

### ISSUE THREAD

**Issue by diaosiji** [TorchCraft/TorchCraft#156]
I am installing StarCraft in different VMware platforms, unfortunately all failed.

On Ubuntu 16.04, I tried to install StarCraft on Win 7, Win 8.1 and Win10 in VMware workstation.

On OSX(10.12.5), I also tried to install StarCraft on Win 7, Win 8.1 and Win10 in VMware fusion.

All attempts end in error: 

After installed StarCraft, and lauched it. The error pops out：

Unable to initialize OpenGL. Please verify that your video card drivers are up to date. The pic is below:
![wechatimg1](https://cloud.githubusercontent.com/assets/11862759/26683289/e3e324e2-4715-11e7-892b-a0a0317d9eb4.jpeg)

However in Gabriel Synnaeve's talk, it seems all works OK between host and virtual machine.

Thanks for any help.

**Comment by edran** [comment]
Hi @diaosiji, we unfortunately don't support StarCraft 1.18. 

See https://github.com/TorchCraft/TorchCraft/blob/develop/docs/user/installation.md#installing-torchcraft.
