### ISSUE TITLE
How can I disable the gui?

### ISSUE THREAD

**Issue by DebangLi** [TorchCraft/TorchCraft#176]
Hellow, I wanna know how to disable the gui of starcraft when i train a model with torchcraft,  because I think it cost too much time using the gui to render. I only find in setup [tcc.set_gui, 1], but I don't know what to do in the server sdie(starcrat),. Should I do something with BWAPI or other things?

**Comment by jgehring** [comment]
AFAIK there's no way to disable the Broodwar UI. You can use the "set_frameskip" command to modify the update rate of the GUI, though. A higher value will result in less updates and thus a faster simulation.

Alternatively, you can also try using OpenBW. See [docs/user/openbw.md](https://github.com/TorchCraft/TorchCraft/blob/master/docs/user/openbw.md) for instructions.

**Comment by DebangLi** [comment]
@jgehring Thank you! When I see "set_gui" in setup, I thought there might be a way to disable. Anyway, thank you so much!

**Comment by jgehring** [comment]
"set_gui" maps to the BWAPI's [setGUI](https://bwapi.github.io/class_b_w_a_p_i_1_1_game.html#af7801eafd1cd90beb0544f6f3275da7b) function. The documentation states "This typically gives Starcraft a very low graphical frame rate and disables all drawing functionality in BWAPI." This means it doesn't actually completely disable the game UI.

**Comment by DebangLi** [comment]
@jgehring  I see. Thank you again!
