### ISSUE TITLE
setting up TorchCraft

### ISSUE THREAD

**Issue by michalsustr** [TorchCraft/TorchCraft#18]
While setting up according to installation instructions, after launcing instance in ChaosLuncher I came across following error:

![selection_179](https://cloud.githubusercontent.com/assets/1756494/21294513/976a018e-c53e-11e6-9a82-9595c68d2353.png)

(it says that it couldn't find SleepConditionVariableCS in KERNEL32.dll)

I run windows XP in virtualbox.

After there is a battle between few marines, and an error message about not being able to find BWEnv.dll, although it is located in C:\Starcraft

![selection_183](https://cloud.githubusercontent.com/assets/1756494/21294582/4adb0dc0-c540-11e6-9f24-65c8f8963341.png)

**Comment by michalsustr** [comment]
Also, when I try to run `BWEnv.exe` I get popup message `Access denied!`

**Comment by spencerduncan** [comment]
Try with these binaries and let me know if you get the same issue.

https://github.com/spencerduncan/TorchCraft/releases/tag/v1.1-0

**Comment by syhw** [comment]
Random guess, BWAPI is not working on your specific setup: is your windows XP the latest service pack?

**Comment by edran** [comment]
@michalsustr do you have any updates about this issue, or are you happy for us to close it?

**Comment by edran** [comment]
Closing as we don't have enough info to debug the issue.
