### ISSUE TITLE
czmq.h Can't be found in vs2013

### ISSUE THREAD

**Issue by cumttang** [TorchCraft/TorchCraft#187]
Though I have already set up bwapi_dir and some others, I met some problem that vs2013 can not found out the head file czmq.h, and czmq directory is empty. How can I do to fix it? Please help:(

In addition, It is on Windows 10.

**Comment by ebetica** [comment]
Do
```
git submodule init
git submodule update
```

**Comment by cumttang** [comment]
You means on Linux?

**Comment by ebetica** [comment]
I'm not sure how you init and update git submodules on Windows, sorry. Visual studio should have an option

**Comment by cumttang** [comment]
Thank you all the same~

**Comment by cumttang** [comment]
E:\github>git submodule init

E:\github>git submodule update
fatal: Not a git repository: E:/github/BWEnv/include/czmq/../../../.git/modules/BWEnv/include/czmq
Failed to clone 'BWEnv/include/czmq'. Retry scheduled
BUG: submodule considered for cloning, doesn't need cloning any more?
fatal: Not a git repository: E:/github/BWEnv/include/czmq/../../../.git/modules/BWEnv/include/czmq
Unable to fetch in submodule path 'BWEnv/include/czmq'

I have tried it, but it still has some problems on VS2013 of Windows. :(

**Comment by pkuso** [comment]
Hi Tommy,

    You may simply git clone czmq & libzmq under the folder
"TorchCraft/BWEnv/include/" through their original links.

    Specifically, "git clone https://github.com/TorchCraft/czmq.git" and
"git clone https://github.com/TorchCraft/libzmq.git".

    Hope that helps.

Regards,
Peng

2017-07-22 16:58 GMT+08:00 TommyTang <notifications@github.com>:

**Comment by cumttang** [comment]
Add the head file to the Include in BWEnv, then it works. Thanks a  lot. Peng

Best Regards,
Tommy
