### ISSUE TITLE
Problem on Install vcrun2013

### ISSUE THREAD

**Issue by cumttang** [TorchCraft/TorchCraft#188]
winetricks -q vcrun2013
When I ran this command on Ubuntu14.04, it occured the Problem that:

tommy@tommy:~$ winetricks -q vcrun2013
------------------------------------------------------
You are using a 64-bit WINEPREFIX. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Unknown arg vcrun2013
Usage: /usr/bin/winetricks [options] [command|verb|path-to-verb] ...
Executes given verbs.  Each verb installs an application or changes a setting.

I don't know why the vcrun2013 is not exists. Please give me a help:(

**Comment by edran** [comment]
If you don't give more information, it's unlikely we can help you out. That said, please do try following the advice of wine:

```
You are using a 64-bit WINEPREFIX. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
```

You are probably running a version that doesn't support the necessary runtime libs. Load the docker as per [instructions](https://github.com/TorchCraft/TorchCraft/blob/8a3b8880785ac0c69f478c30da7eacf3b7b8d411/docker/README.md), and you should be able to get it working.

**Comment by ebetica** [comment]
Closing because of lack of new information, please reopen if this is still a problem for you.
