### ISSUE TITLE
Cannot find 'BWAPI.obj'

### ISSUE THREAD

**Issue by GaoFangshu** [TorchCraft/TorchCraft#189]
I try to compile `BWEnv` but there is an error: `error LNK1104: cannot open “F:\StarCraft\BWAPI.obj”`.
What should I do to fix it? Thank you.

**Comment by edran** [comment]
It's highly likely that the linker cannot write in `F:\StarCraft`. Set the permissions accordingly and try again.

**Comment by GaoFangshu** [comment]
Thank you!
