### ISSUE TITLE
deepmind lab with unity3d and torch

### ISSUE THREAD

**Issue by ahhuang** [TorchCraft/TorchCraft#19]
anybody interested in  deepmind lab, but the engine would be unity3d  instead of quake3, and the RL part would be torch instead of deepmind?

**Comment by spencerduncan** [comment]
I get why you might want to use Torch, but why unity3d instead of quake? I feel like the quake engine would be a much more stable platform for the high number of trials required for deep learning, and it's open source.

**Comment by ahhuang** [comment]
i know quake is open source and is much easier to integrate with DRL projects like torch or tensorflow, but unity3d is much much more popular especially in mobile platforms. so if we want to make use of game engines for doing DRL research, maybe quake is a better choice, but if we want to make use of DRL in video games, unity3d is a better choice. i think lots of ppl have done lots of research, maybe we could make some effort to push them to business. 
"Hey, programmers and designers, wanna put some cool stuffs in your games?"
"Sure"

**Comment by spencerduncan** [comment]
What kind of "cool stuffs" were you thinking of marketing?

**Comment by ahhuang** [comment]
i don't know specifically , i am just thinking, if game developers can use DRL easily , they can figure it out.

**Comment by syhw** [comment]
Note that there is UETorch https://github.com/facebook/UETorch :)

**Comment by edran** [comment]
Thank you for the input :) We are setting up a forum for this kind of discussions - we'll put the link in the README Soon™.
