### ISSUE TITLE
Git clone error when install the Torch client (Linux)

### ISSUE THREAD

**Issue by JIElite** [TorchCraft/TorchCraft#199]
I follow [this document](https://github.com/TorchCraft/TorchCraft/blob/master/docs/user/installation.md#installing-the-torch-client-linux) to install Torch client on Ubuntu 14.04.5 LTS

when I install TorchCraft by typing:
`git clone git@github.com:torchcraft/torchcraft.git --recursive`

It cause error:

> Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.
>
>Please make sure you have the correct access rights
and the repository exists.

How should I fix it? Could I just use `git clone https://github.com/TorchCraft/TorchCraft.git --recursive` as a substitite?

**Comment by edran** [comment]
Yes, please go ahead with that. I'll change all the git links in the docs to https links.
