### ISSUE TITLE
BWAPI on Linux Problem_Running AIModule

### ISSUE THREAD

**Issue by JunhyeonPark** [TorchCraft/TorchCraft#20]
I read recent tutorial about TorchCraft and follow tutorial "BWAPI in Linux",
 but when I try to implement 
"wine bwheadless.exe -e $STARCRAFT/StarCraft.exe -l $STARCRAFT/bwapi-data/BWAPI.dll --headful",
which is used for connecting BWAPI and Starcraft, it freeze like below figures.

Can someone help me?

![2016-12-26 20-32-50](https://cloud.githubusercontent.com/assets/24790325/21497116/4e10b5c6-cc66-11e6-9859-9d70d55eb017.png)

![2016-12-26 20-33-00](https://cloud.githubusercontent.com/assets/24790325/21497144/75a8d6e0-cc66-11e6-8e91-70d7a06d21b8.png)

wine --version : wine-1.6.2 (I set WINEARCH=win32 WINEPREFIX=~/.wine wine wineboot)
Ubuntu --version : 16.04
Starcraft --version : 1.16.1
BWAPI --version : 4.1.2

-----------------------------------------------------------------------------------------------------------------------------------------
I tried other command,
wine /desktop=foo, 800x600 bwheadless.exe -e $STARCRAFT/StarCraft.exe -l bwapi-data/BWAPI.dll --headful

wine explorer /desktop=foo, 800x600 bwheadless.exe -e $STARCRAFT/StarCraft.exe -l bwapi-data/BWAPI.dll --headful
but they don't work like below figures

![2016-12-27 12-48-32](https://cloud.githubusercontent.com/assets/24790325/21497421/1202cfae-cc68-11e6-9d9a-95d8d536481d.png)

![2016-12-27 12-50-36](https://cloud.githubusercontent.com/assets/24790325/21497422/1672d00c-cc68-11e6-8fd1-a94cc3e3e461.png)

**Comment by spencerduncan** [comment]
You need to start one of the lua scripts for the DLL to talk to, or it will just hang on the first frame when the game starts.

**Comment by JunhyeonPark** [comment]
Can you tell me more details? Sorry, I can't understand what lua scripts is saying...
Or, do you have any other posts to refer for BWAPI on LINUX

**Comment by spencerduncan** [comment]
Sorry, let me explain better.

TorchCraft is an API for using Torch with BWAPI. [Torch is a scientific computing framework](http://torch.ch/) with many useful tools for machine learning among other things. Torch uses the [lua scripting language.](https://www.lua.org/) The part of TorchCraft that runs in BWAPI just packs data and sends it to a Torch/Lua script. The lua part is where all the actual logic and AI happens. Check out the examples directory for some examples.

The only time you need to change the BWAPI code is if you want to change what data is communicated between Lua and BWAPI. That part of the code needs to be compiled with Visual Studio, but you can grab the latest release from the release section.

To actually get a script running you need to first make sure you have `BWEnv.dll` in your StarCraft directory. Then, open up `$STARCRAFT/bwapi-data/bwapi.ini`. That file should start with the `[ai]` section. Check that `ai=BWEnv.dll` is set in that section. Then, start StarCraft like you were before. After that, go to the examples folder in the TorchCraft repository and run `th simple_dll.lua -t localhost`. It usually works better to wait until you've started the torch script before hitting start in the StarCraft lobby.

**Comment by spencerduncan** [comment]
Also, your wine is very out of date; the latest stable release is 1.8.6.

**Comment by JunhyeonPark** [comment]
I finally understood how to run TorchCraft correctly, thanks for great explanation :)
