### ISSUE TITLE
Load BWEnv.dll error

### ISSUE THREAD

**Issue by JIElite** [TorchCraft/TorchCraft#201]
**Environment:**
Starcraft Brood War 1.16.1, TorchCraft Server (BWEnv.dll): Windows7
TorchCraft Client (simple_dll.lua): Ubuntu 14.04.5 LTS
BWAPI 4.2.0

**Problem**
When I config `ai = BWEnv.dll`  in `bwapi.ini` and launch Chaoslauncher, the SC:BW always crashed, a stop at initial game state like:
![](https://i.imgur.com/zlXn5Vu.png)

When I remove BWEnv.dll as: `ai = NULL`, BWAPI will work appropriately.
I think this problem may caused by using wrong BWAPI.dll which is not suitable for TorchCraft
Could you offer the instructions to build BWAPI.dll? 

Thank you.

**Comment by edran** [comment]
`BWEnv.dll` will certainly block until there's an active connection to a TorchCraft client. Then it's up to the client to unlock BW's loop by running the send / receive loop. Please have a look at any of the examples :)

**Comment by JIElite** [comment]
Thank you, I've already solved my problem. And here are some feedback:

TorchCraft 1.3.0 is not compatible with BWAPI 4.2.0 on both Windows7 and Windows 10, But work well with BWAPI 4.1.2. I've tested it on Windows10 in traditional Chinese version.
![](https://i.imgur.com/oWjnPET.jpg)

**Comment by edran** [comment]
Awesome, hope you enjoy the framework! :) 

>TorchCraft 1.3.0 is not compatible with BWAPI 4.2.0 on both Windows7 and Windows 10, But work well with BWAPI 4.1.2. I've tested it on Windows10 in traditional Chinese version.

That's indeed the case, however `develop` has been updated to 4.2.0. We are going to make a new release Soon™.

Closing as this issue has been solved.
