### ISSUE TITLE
Setting up TorchCraft both client and server at same local

### ISSUE THREAD

**Issue by JunhyeonPark** [TorchCraft/TorchCraft#21]
I setting up all the TorchCraft setting on local, but another problem occur.

When I try to run simple_dll.lua in examples, game ended immediately like below fig 4,5)

Can someone help to know cause?

![a2](https://cloud.githubusercontent.com/assets/24790325/21603692/7d07229e-d1e2-11e6-87cf-02044c8a4716.png)
fig.1) Check Map is correct - m5v5_c_far.scm is implemented well without TorchCraft

![a1](https://cloud.githubusercontent.com/assets/24790325/21603689/72ced524-d1e2-11e6-825c-6522c9572ad1.png)
fig.2) All the bwapi-data and $STARCRAFT setting is already set correctly following BWAPI ON LINUX tutorial

![a5](https://cloud.githubusercontent.com/assets/24790325/21603766/d458b26a-d1e2-11e6-8d2f-4f06cbfa1037.png)
fig.3) Check BWAPI work fine through running Iron.dll bot

![a3](https://cloud.githubusercontent.com/assets/24790325/21604161/ef26aa46-d1e4-11e6-8b14-c5b438068da4.png)

![a4](https://cloud.githubusercontent.com/assets/24790325/21603797/0dbbf648-d1e3-11e6-90a3-838f326099a9.png)
fig.4, 5) But when I try to run simple_dll.lua, game ended immediately

Specification)
wine --version : wine-1.6.2 -> wine-1.8 (I tried both version, but same error)
Ubuntu --version : 16.04
Starcraft --version : 1.16.1
BWAPI --version : 4.1.2

**Comment by jchassoul** [comment]
Hi there, I'm going to try to reproduce your error today, I'm considering at what point make more sense to have a completely legal virtual machine on windows just for starcraft but now that I see how awesome your screenshots looks I'm into setting this properly.

**Comment by spencerduncan** [comment]
Try replacing your BWEnv.dll with the one here:
https://github.com/spencerduncan/TorchCraft/releases/tag/v1.1-0

And while we're posting cool screen shots:
![Screenshot](https://images.discordapp.net/.eJwFwVEKhCAQANC7-J86YzpOlwkxsaAydIKFZe--733V20-1qF3kGYsx2zFy65se0nqqRdfW6lnScwyd22WSSMr7VW4ZBp0LgQgC0gyMjoNBT0jWc2SKjsDH2aCFMAFOYCeY0TpegSF-wBKvI_cm-rmr-v0BnL8oNQ.HcgysY2MihNtl8KSPH-L_MU_iYE)

**Comment by jchassoul** [comment]
yay! cool screen shots! (= your i3 looks obviously more awesome, hope the fix you attached it's also the cure for my lack of bw competition!

**Comment by spencerduncan** [comment]
They just pushed a new official release. It's probably better to use that instead of what I linked earlier.

https://github.com/TorchCraft/TorchCraft/releases

**Comment by JunhyeonPark** [comment]
After replacing new torchcraft 1.0.2, simple_dll.lua work well for iteration total_battles = 40!
There are some cases which can't connect torch to Starcraft, but it seems just wine problem.
Thanks for all!

**Comment by spencerduncan** [comment]
> There are some cases which can't connect torch to Starcraft, but it seems just wine problem.

It might just be BWAPI. Sometimes it takes a couple tries to load an AI, which is why you get a lot of downtime in SSAIT sometimes.
