### ISSUE TITLE
Lua bridge: Address warnings

### ISSUE THREAD

**Issue by dgant** [TorchCraft/TorchCraft#218]
We should either fix these or acknowledge them and add pragmas.

`/torchcraft/lua/state_lua.cpp: In function 'void {anonymous}::updateUserValueAndPush(lua_State*, torchcraft::State*, const string&, int)':
/torchcraft/lua/state_lua.cpp:259:28: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (lua_tointeger(L, -1) == s->numUpdates) {
                            ^
/torchcraft/lua/state_lua.cpp:280:13: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if (p != s->neutral_id) {
             ^
/torchcraft/lua/state_lua.cpp:289:13: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       if (p != s->neutral_id) {
             ^
/torchcraft/lua/replayer_lua.cpp: In function 'int replayerGetMap(lua_State*)':
/torchcraft/lua/replayer_lua.cpp:198:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < start_loc_x.size(); i++) {
                     ^
In file included from /torchcraft/lua/gamestore.cpp:10:0:
/torchcraft/lua/gamestore.h: In constructor 'torchcraft::replayer::CircularBuffer::CircularBuffer(size_t)':
/torchcraft/lua/gamestore.h:47:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i < size; i++) {
                       ^
/torchcraft/lua/gamestore.h: In destructor 'torchcraft::replayer::CircularBuffer::~CircularBuffer()':
/torchcraft/lua/gamestore.h:54:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i < size; i++) {
                       ^
/torchcraft/lua/gamestore.h: In member function 'void torchcraft::replayer::CircularBuffer::clear()':
/torchcraft/lua/gamestore.h:87:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i < size; i++) {
                       ^
In file included from /torchcraft/lua/init.cpp:24:0:
/torchcraft/lua/gamestore.h: In constructor 'torchcraft::replayer::CircularBuffer::CircularBuffer(size_t)':
/torchcraft/lua/gamestore.h:47:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i < size; i++) {
                       ^
/torchcraft/lua/gamestore.h: In destructor 'torchcraft::replayer::CircularBuffer::~CircularBuffer()':
/torchcraft/lua/gamestore.h:54:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i < size; i++) {
                       ^
/torchcraft/lua/gamestore.h: In member function 'void torchcraft::replayer::CircularBuffer::clear()':
/torchcraft/lua/gamestore.h:87:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i < size; i++) {
`

**Comment by jgehring** [comment]
Thanks for noting this! Yep, those should be fixed.

**Comment by dgant** [comment]
Resolved via https://github.com/TorchCraft/TorchCraft/pull/228
