### ISSUE TITLE
Application of frame diffs in State is broken

### ISSUE THREAD

**Issue by jgehring** [TorchCraft/TorchCraft#221]
@ebetica in #214 you removed code in `replayer::detail::add()` with a comment stating that this would fix loading of units in replayer (9a3f6772bbe7521a6fdab61d47c9915d0f861042). However, this breaks client-server communication since State tries to apply the frame diff in place (that's why we added the `std::move` in the first place). What failures did you observe exactly when testing this on dumped replays?

**Comment by dgant** [comment]
Will fix this since I'm testing all these cases anyhow

**Comment by ebetica** [comment]
Fixed in #237
