### ISSUE TITLE
error in install py

### ISSUE THREAD

**Issue by Kyle1993** [TorchCraft/TorchCraft#239]
python can't import torchcraft, get this error:
```
ImportError: /home/jianglibin/py3env/lib/python3.5/site-packages/torchcraft.cpython-35m-x86_64-linux-gnu.so: undefined symbol: ZSTD_CStreamInSize

```

How to handle this?

**Comment by ebetica** [comment]
Please install zstd 1.1.4+

**Comment by Kyle1993** [comment]
I have installed zstd 1.3.1, still have this problem
```
(py3env) jianglibin@cis-BIG:~$ zstd -V
*** zstd command line interface 64-bits v1.3.1, by Yann Collet ***
(py3env) jianglibin@cis-BIG:~$ ipython3
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import torchcraft
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-12ee3e670892> in <module>()
----> 1 import torchcraft

ImportError: /home/jianglibin/py3env/lib/python3.5/site-packages/torchcraft.cpython-35m-x86_64-linux-gnu.so: undefined symbol: ZSTD_CStreamInSize

In [2]: 
```

**Comment by ebetica** [comment]
And you compiled it with zstd 1.3.1? It looks like it's not finding the right zstd libraries, or finding it at all...

**Comment by Kyle1993** [comment]
@ebetica 
I just download it from github ( https://github.com/facebook/zstd )and "make install"
is it correct?

**Comment by ebetica** [comment]
That should be correct... Does `readelf -d /home/jianglibin/py3env/lib/python3.5/site-packages/torchcraft.cpython-35m-x86_64-linux-gnu.so` show the correct zstd as being linked?

**Comment by Kyle1993** [comment]
@ebetica 
it seems has been linked
```
Dynamic section at offset 0x113740 contains 29 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libzstd.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libzmq.so.5]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [ld-linux-x86-64.so.2]
```
but I find I have many libzstd.so, is't link correct?
```
(py3env) jianglibin@cis-BIG:/usr/lib/x86_64-linux-gnu$ ls libzstd*
libzstd.a  libzstd.so  libzstd.so.0  libzstd.so.0.5.1
```

**Comment by ebetica** [comment]
Yes, it appears as if you linked zstd 0.5.1, not whatever newest version. Try removing the older versions, or pass in the location to the newer version in your LD_LIBRARY_PATH first.

**Comment by Kyle1993** [comment]
Wow it works, thanks so much @ebetica 
but I meet a new problem, when I start the windows's client, it works well, but when I start my linux server(python,th get the same problem), the windows client crash, get message "Segmentation fault (core dumped)" on linux, I use win10, bwapi4.12, win7 get same problem.

**Comment by Kyle1993** [comment]
Wow it works, thanks so much @ebetica 
but I meet a new problem, when I start the windows's client, it works well, but when I start my linux server(python,th get the same problem), the windows client crash, get message "Segmentation fault (core dumped)" on linux, I use win10, bwapi4.12, win7 get same problem.
![Uploading 1.PNG…]()

**Comment by Kyle1993** [comment]
Wow it works, thanks so much @ebetica 
but I meet a new problem, when I start the windows's client, it works well, but when I start my linux server(python,th get the same problem), the windows client crash, get message "Segmentation fault (core dumped)" on linux, I use win10, bwapi4.12, win7 get same problem.

**Comment by ebetica** [comment]
Have you tried the develop branch @Kyle1993 ? We're likely going to do a release very soon. It also has a better README.md. If you are on master, I think win10 does not work there. What you might be able to do is compile in debug model (add -g -O0 to the setup.py) and then use gdb to see where it's segfaulting at. I suspect it's because there's a client / server version mismatch somewhere.

**Comment by Kyle1993** [comment]
![c](https://user-images.githubusercontent.com/20033328/33979667-5cf17726-e0e0-11e7-9242-3d64122b5d65.PNG)
this is the error report on win7, it seem that the version czmq is 3, in linux I install zeromq4.2.0 , and I also install the libzmq3-dev, is it correct?
```
(py3env) jianglibin@Titan:~$ sudo apt-get install libzmq3-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libzmq3-dev is already the newest version (4.1.4-7).
The following packages were automatically installed and are no longer required:
  linux-headers-4.4.0-78 linux-headers-4.4.0-78-generic linux-headers-4.4.0-79
  linux-headers-4.4.0-79-generic linux-headers-4.4.0-81 linux-headers-4.4.0-81-generic
  linux-headers-4.4.0-87 linux-headers-4.4.0-87-generic linux-headers-4.4.0-92
  linux-headers-4.4.0-92-generic linux-headers-4.4.0-96 linux-headers-4.4.0-96-generic
  linux-headers-4.4.0-97 linux-headers-4.4.0-97-generic linux-headers-4.4.0-98
  linux-headers-4.4.0-98-generic linux-image-4.4.0-47-generic linux-image-4.4.0-78-generic
  linux-image-4.4.0-79-generic linux-image-4.4.0-81-generic linux-image-4.4.0-87-generic
  linux-image-4.4.0-92-generic linux-image-4.4.0-96-generic linux-image-4.4.0-97-generic
  linux-image-4.4.0-98-generic linux-image-extra-4.4.0-47-generic
  linux-image-extra-4.4.0-78-generic linux-image-extra-4.4.0-79-generic
  linux-image-extra-4.4.0-81-generic linux-image-extra-4.4.0-87-generic
  linux-image-extra-4.4.0-92-generic linux-image-extra-4.4.0-96-generic
  linux-image-extra-4.4.0-97-generic linux-image-extra-4.4.0-98-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 219 not upgraded.
```

**Comment by ebetica** [comment]
What version of torchcraft are you using? Master? And what version of the client did you use? Did you compile your own or did you take the release?

**Comment by Kyle1993** [comment]
I have tried both master and develop branch, sc1 client version is 1.16.1 with broodwar patch, both version 4.12 and 4.20 of bwapi have tried in master branch, I just take the release of py.
in python3 the client can connect and init well , but when client.send([]), starcraft crash
```
import torchcraft.Constants as tcc
import torchcraft as tc

ip = '172.18.217.172'
port = 11111

client = tc.Client()
client.connect(ip,port)
state = client.init(micro_battles=True)
print('ok client.init')

# client.send([])    # sc crash here

client.send([      # sc crash here 
        [tcc.set_speed, 0],
        [tcc.set_gui, 1],
        [tcc.set_cmd_optim, 1],
    ])
```

**Comment by Kyle1993** [comment]
@ebetica How to check torchcraft link to correct libzmq.so?

**Comment by ebetica** [comment]
You're sure the BWEnv.dll is compiled from the right version in visual studio?

**Comment by Kyle1993** [comment]
I didn't compile the code , just take the release, is it ok?

**Comment by Kyle1993** [comment]
maybe 3 months age, it used to work well on the version which have the th dependency(not on the same computer). How can I find the version back.

**Comment by Kyle1993** [comment]
I find and reinstall the earlier version with th dependency, it's works well, This is really strange.

**Comment by ebetica** [comment]
It's because the client server communication has changed quite a bit. To use the develop version you'll need to compile a BWEnv.so on your own.

**Comment by Kyle1993** [comment]
I try to compile the develop version with vs2017, but get lots error, it's very appreciate if you can provide the release of develop version

**Comment by dgant** [comment]
@Kyle1993 I'm afraid the develop branch doesn't currently build on Windows. I'm working on it at https://github.com/TorchCraft/TorchCraft/tree/visual-studio-fixes but may not be able to merge that into develop any time soon. You could give that branch a try -- I forget if it's currently working but it should at least be much closer.

**Comment by ebetica** [comment]
Hey @Kyle1993, I just made a new release, if you're still having trouble try it, it has a prebuilt .dll on master. https://github.com/TorchCraft/TorchCraft/releases/tag/v1.4.0

**Comment by Kyle1993** [comment]
@ebetica Thanks so much，But I use the earlier version, it works well and has almost fulfilled my needs.

**Comment by ebetica** [comment]
Closing because it sounds like your issue is resolved. Feel free to reopen if it's not resolved.
