### ISSUE TITLE
Python client segfaults when given empty commands

### ISSUE THREAD

**Issue by edran** [TorchCraft/TorchCraft#247]
To reproduce:

```python
>>> import torchcraft
>>> tc = torchcraft.Client()
<torchcraft.Client at 0xwhatever>
>>> tc.connect('localhost', 11111)
True
>>>tc.send([[]])
Segmentation fault (core dumped)
```

This is likely because we simply don't handle this well both in the backend and in pybind. We might want to look into how to crash more gracefully (e.g. crash the client, but tell the user that happened so that they can try reconnecting)?

**Comment by jgehring** [comment]
This is because the code in question accesses the first element of the command vector before checking its length: https://github.com/TorchCraft/TorchCraft/blob/master/py/pyclient.cpp#L48. Will fix.

**Comment by jgehring** [comment]
Fixed in devleop
