### ISSUE TITLE
The installation step for python client

### ISSUE THREAD

**Issue by JIElite** [TorchCraft/TorchCraft#251]
If we just want to use python as our TorchCraft client, we don't need to follow the tutorial as [here](https://github.com/TorchCraft/TorchCraft/blob/master/docs/user/starcraft_in_windows.md#torchcraft), right?

Just change our directory to torchcraft, and typing:
`pip install -e .`
and we can start programming.

I didn't find the tutorial about install python client, so I post this issue to confirm.

**Comment by dgant** [comment]
Hi @JIElite . Exactly which steps are you asking about skipping?

You'll still need BWEnv to act as your TorchCraft server. That's what connects to Brood War and sends/receives messages with your Python client.

**Comment by ebetica** [comment]
@JIElite If you're talking about the last section with using lua, yes that is correct, just use the Python client. BWEnv as the AIModule should cause your StarCraft to hang on start while waiting for the client, and after you run your python script all will be well.

**Comment by JIElite** [comment]
@ebetica Yes, I'm talking about the client part. Thank you.
