### ISSUE TITLE
Missing BWAPI_LIBRARY BWAPI_INCLUDE_DIR during CMake

### ISSUE THREAD

**Issue by tshrjn** [TorchCraft/TorchCraft#255]
After installing `czmq`, `zeromq` via `brew`  (using macOS 10.11) and  openbw/bwapi (https://github.com/openbw/bwapi), cmake for `BWEnv` throws cound not find BWAPI. I faced this exact same issue on ubuntu as well but was resolved by passing the BWAPI and OPENBWAPI paths as arguments like this:
```
cmake .. -DCMAKE_BUILD_TYPE=relwithdebinfo -DBWAPI_DIR=../../../bwapi/bwapi -DOPENBW_DIR=../../../openbw/mini-openbwapi  && make -j
```
and I tried this by passing relative and full path. Each time, the following error was thrown:

```
CMake Error at /usr/local/Cellar/cmake/3.10.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find BWAPI (missing: BWAPI_LIBRARY BWAPI_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.10.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  FindBWAPI.cmake:11 (find_package_handle_standard_args)
  CMakeLists.txt:36 (find_package)


-- Configuring incomplete, errors occurred!
See also "/Users/tshrjn/TorchCraft/BWEnv/build/CMakeFiles/CMakeOutput.log".
```

**Comment by ebetica** [comment]
Did you install bwapi as shown here: https://github.com/openbw/bwapi ?

**Comment by tshrjn** [comment]
Yes, did the installation as stated on https://github.com/openbw/bwapi and only then was I refering to their respective directories.

**Comment by ebetica** [comment]
The CMakeLists looks for 
- `/Users/tshrjn/bwapi/bwapi/include/BWAPI.h`
- `/Users/tshrjn/bwapi/bwapi/include/BWAPI/*.h`
- `/Users/tshrjn/bwapi/bwapi/lib/libBWAPI.so`
- `/Users/tshrjn/bwapi/bwapi/lib/libBWAPILIB.so`
- `/Users/tshrjn/bwapi/bwapi/lib/libBWAPIClient.a`

If any of these are not there, then you failed in building openbw. Can you verify this?
