### ISSUE TITLE
Not able to send restart command to server

### ISSUE THREAD

**Issue by apsdehal** [TorchCraft/TorchCraft#256]
When sending `[[tcc.restart]]` from python client to server using `client.send` server throws an error: 
`Error: execute_action: unknown action 8`

**Comment by ebetica** [comment]
Please use quit for OpenBW. It doesn't implement restart. Start times should be trivial compared to the default client, so it's not as big of a deal here.

**Comment by apsdehal** [comment]
Closing as not fixable.
