### ISSUE TITLE
Trouble installing Torchcraft

### ISSUE THREAD

**Issue by rrz5013** [TorchCraft/TorchCraft#285]
I'm not sure whether I'm missing some module, but everytime I install Torchcraft I get this trace: 

ray@ray-VirtualBox:~/Downloads/StarData/TorchCraft$ pip install .
Processing /home/ray/Downloads/StarData/TorchCraft
Requirement already satisfied: pybind11>=2.1 in /home/ray/envs/artse/bin/sqlalchemy/lib/python3.6/site-packages (from torchcraft==1.4.0) (2.2.3)
Installing collected packages: torchcraft
  Running setup.py install for torchcraft ... error
    Complete output from command /home/ray/envs/artse/bin/sqlalchemy/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-lte4l5an/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-czrk5zcp/install-record.txt --single-version-externally-managed --compile --install-headers /home/ray/envs/artse/bin/sqlalchemy/include/site/python3.6/torchcraft:
    ['py/pystate.cpp', 'py/pyconstants.cpp', 'py/pytorchcraft.cpp', 'py/pyclient.cpp', 'py/pyreplayer.cpp', 'replayer/frame_diff.cpp', 'replayer/replayer.cpp', 'replayer/frame_serialization.cpp', 'replayer/frame_diff_serialization.cpp', 'replayer/frame.cpp', 'client/constants.cpp', 'client/state.cpp', 'client/constants_static.cpp', 'client/connection.cpp', 'client/client.cpp']
    running install
    running build
    running build_ext
    building 'torchcraft' extension
    creating build
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/py
    creating build/temp.linux-x86_64-3.6/replayer
    creating build/temp.linux-x86_64-3.6/client
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.6-EKG1lX/python3.6-3.6.5=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWITH_ZSTD -I/home/ray/envs/artse/bin/sqlalchemy/include/site/python3.6 -I/home/ray/envs/artse/bin/sqlalchemy/include/site/python3.6 -Iinclude/torchcraft -Iinclude -Ireplayer -I. -IBWEnv/fbs -I/home/ray/envs/artse/bin/sqlalchemy/include -I/usr/include/python3.6m -c py/pystate.cpp -o build/temp.linux-x86_64-3.6/py/pystate.o -DVERSION_INFO="1.4.0" -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.6-EKG1lX/python3.6-3.6.5=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWITH_ZSTD -I/home/ray/envs/artse/bin/sqlalchemy/include/site/python3.6 -I/home/ray/envs/artse/bin/sqlalchemy/include/site/python3.6 -Iinclude/torchcraft -Iinclude -Ireplayer -I. -IBWEnv/fbs -I/home/ray/envs/artse/bin/sqlalchemy/include -I/usr/include/python3.6m -c py/pyconstants.cpp -o build/temp.linux-x86_64-3.6/py/pyconstants.o -DVERSION_INFO="1.4.0" -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.6-EKG1lX/python3.6-3.6.5=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWITH_ZSTD -I/home/ray/envs/artse/bin/sqlalchemy/include/site/python3.6 -I/home/ray/envs/artse/bin/sqlalchemy/include/site/python3.6 -Iinclude/torchcraft -Iinclude -Ireplayer -I. -IBWEnv/fbs -I/home/ray/envs/artse/bin/sqlalchemy/include -I/usr/include/python3.6m -c py/pytorchcraft.cpp -o build/temp.linux-x86_64-3.6/py/pytorchcraft.o -DVERSION_INFO="1.4.0" -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from /home/ray/envs/artse/bin/sqlalchemy/include/site/python3.6/pybind11/pytypes.h:12:0,
                     from /home/ray/envs/artse/bin/sqlalchemy/include/site/python3.6/pybind11/cast.h:13,
                     from /home/ray/envs/artse/bin/sqlalchemy/include/site/python3.6/pybind11/attr.h:13,
                     from /home/ray/envs/artse/bin/sqlalchemy/include/site/python3.6/pybind11/pybind11.h:43,
                     from py/pytorchcraft.h:2,
                     from py/pytorchcraft.cpp:1:
    py/pytorchcraft.cpp: In function ‘PyObject* PyInit_torchcraft()’:
    /home/ray/envs/artse/bin/sqlalchemy/include/site/python3.6/pybind11/detail/common.h:242:34: warning: ‘PyObject* pybind11_init()’ is deprecated: PYBIND11_PLUGIN is deprecated, use PYBIND11_MODULE [-Wdeprecated-declarations]
                 return pybind11_init();                                            \
                                      ^
    py/pytorchcraft.cpp:10:1: note: in expansion of macro ‘PYBIND11_PLUGIN’
     PYBIND11_PLUGIN(torchcraft) {
     ^~~~~~~~~~~~~~~
    /home/ray/envs/artse/bin/sqlalchemy/include/site/python3.6/pybind11/detail/common.h:227:22: note: declared here
         static PyObject *pybind11_init();                                          \
                          ^
    py/pytorchcraft.cpp:10:1: note: in expansion of macro ‘PYBIND11_PLUGIN’
     PYBIND11_PLUGIN(torchcraft) {
     ^~~~~~~~~~~~~~~
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.6-EKG1lX/python3.6-3.6.5=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWITH_ZSTD -I/home/ray/envs/artse/bin/sqlalchemy/include/site/python3.6 -I/home/ray/envs/artse/bin/sqlalchemy/include/site/python3.6 -Iinclude/torchcraft -Iinclude -Ireplayer -I. -IBWEnv/fbs -I/home/ray/envs/artse/bin/sqlalchemy/include -I/usr/include/python3.6m -c py/pyclient.cpp -o build/temp.linux-x86_64-3.6/py/pyclient.o -DVERSION_INFO="1.4.0" -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.6-EKG1lX/python3.6-3.6.5=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWITH_ZSTD -I/home/ray/envs/artse/bin/sqlalchemy/include/site/python3.6 -I/home/ray/envs/artse/bin/sqlalchemy/include/site/python3.6 -Iinclude/torchcraft -Iinclude -Ireplayer -I. -IBWEnv/fbs -I/home/ray/envs/artse/bin/sqlalchemy/include -I/usr/include/python3.6m -c py/pyreplayer.cpp -o build/temp.linux-x86_64-3.6/py/pyreplayer.o -DVERSION_INFO="1.4.0" -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.6-EKG1lX/python3.6-3.6.5=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWITH_ZSTD -I/home/ray/envs/artse/bin/sqlalchemy/include/site/python3.6 -I/home/ray/envs/artse/bin/sqlalchemy/include/site/python3.6 -Iinclude/torchcraft -Iinclude -Ireplayer -I. -IBWEnv/fbs -I/home/ray/envs/artse/bin/sqlalchemy/include -I/usr/include/python3.6m -c replayer/frame_diff.cpp -o build/temp.linux-x86_64-3.6/replayer/frame_diff.o -DVERSION_INFO="1.4.0" -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.6-EKG1lX/python3.6-3.6.5=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWITH_ZSTD -I/home/ray/envs/artse/bin/sqlalchemy/include/site/python3.6 -I/home/ray/envs/artse/bin/sqlalchemy/include/site/python3.6 -Iinclude/torchcraft -Iinclude -Ireplayer -I. -IBWEnv/fbs -I/home/ray/envs/artse/bin/sqlalchemy/include -I/usr/include/python3.6m -c replayer/replayer.cpp -o build/temp.linux-x86_64-3.6/replayer/replayer.o -DVERSION_INFO="1.4.0" -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from replayer/replayer.cpp:14:0:
    replayer/zstdstream.h:22:10: fatal error: zstd.h: No such file or directory
     #include <zstd.h>
              ^~~~~~~~
    compilation terminated.
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.6-EKG1lX/python3.6-3.6.5=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWITH_ZSTD -I/home/ray/envs/artse/bin/sqlalchemy/include/site/python3.6 -I/home/ray/envs/artse/bin/sqlalchemy/include/site/python3.6 -Iinclude/torchcraft -Iinclude -Ireplayer -I. -IBWEnv/fbs -I/home/ray/envs/artse/bin/sqlalchemy/include -I/usr/include/python3.6m -c replayer/frame_diff_serialization.cpp -o build/temp.linux-x86_64-3.6/replayer/frame_diff_serialization.o -DVERSION_INFO="1.4.0" -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.6-EKG1lX/python3.6-3.6.5=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWITH_ZSTD -I/home/ray/envs/artse/bin/sqlalchemy/include/site/python3.6 -I/home/ray/envs/artse/bin/sqlalchemy/include/site/python3.6 -Iinclude/torchcraft -Iinclude -Ireplayer -I. -IBWEnv/fbs -I/home/ray/envs/artse/bin/sqlalchemy/include -I/usr/include/python3.6m -c replayer/frame.cpp -o build/temp.linux-x86_64-3.6/replayer/frame.o -DVERSION_INFO="1.4.0" -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.6-EKG1lX/python3.6-3.6.5=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWITH_ZSTD -I/home/ray/envs/artse/bin/sqlalchemy/include/site/python3.6 -I/home/ray/envs/artse/bin/sqlalchemy/include/site/python3.6 -Iinclude/torchcraft -Iinclude -Ireplayer -I. -IBWEnv/fbs -I/home/ray/envs/artse/bin/sqlalchemy/include -I/usr/include/python3.6m -c client/constants.cpp -o build/temp.linux-x86_64-3.6/client/constants.o -DVERSION_INFO="1.4.0" -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.6-EKG1lX/python3.6-3.6.5=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWITH_ZSTD -I/home/ray/envs/artse/bin/sqlalchemy/include/site/python3.6 -I/home/ray/envs/artse/bin/sqlalchemy/include/site/python3.6 -Iinclude/torchcraft -Iinclude -Ireplayer -I. -IBWEnv/fbs -I/home/ray/envs/artse/bin/sqlalchemy/include -I/usr/include/python3.6m -c client/state.cpp -o build/temp.linux-x86_64-3.6/client/state.o -DVERSION_INFO="1.4.0" -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.6-EKG1lX/python3.6-3.6.5=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWITH_ZSTD -I/home/ray/envs/artse/bin/sqlalchemy/include/site/python3.6 -I/home/ray/envs/artse/bin/sqlalchemy/include/site/python3.6 -Iinclude/torchcraft -Iinclude -Ireplayer -I. -IBWEnv/fbs -I/home/ray/envs/artse/bin/sqlalchemy/include -I/usr/include/python3.6m -c client/constants_static.cpp -o build/temp.linux-x86_64-3.6/client/constants_static.o -DVERSION_INFO="1.4.0" -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.6-EKG1lX/python3.6-3.6.5=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DWITH_ZSTD -I/home/ray/envs/artse/bin/sqlalchemy/include/site/python3.6 -I/home/ray/envs/artse/bin/sqlalchemy/include/site/python3.6 -Iinclude/torchcraft -Iinclude -Ireplayer -I. -IBWEnv/fbs -I/home/ray/envs/artse/bin/sqlalchemy/include -I/usr/include/python3.6m -c client/connection.cpp -o build/temp.linux-x86_64-3.6/client/connection.o -DVERSION_INFO="1.4.0" -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from client/connection.h:14:0,
                     from client/connection.cpp:14:
    client/../BWEnv/include/zmq.hpp:42:10: fatal error: zmq.h: No such file or directory
     #include <zmq.h>
              ^~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/ray/envs/artse/bin/sqlalchemy/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-lte4l5an/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-czrk5zcp/install-record.txt --single-version-externally-managed --compile --install-headers /home/ray/envs/artse/bin/sqlalchemy/include/site/python3.6/torchcraft" failed with error code 1 in /tmp/pip-req-build-lte4l5an/

**Comment by dgant** [comment]
Hi @rrz5013 . Is this on the develop branch? If so I might have caused this.

**Comment by rrz5013** [comment]
I get the error on master as well as develop.

**Comment by dgant** [comment]
Did you do a `git submodule update --init --recursive` ? This is required to clone libzmq

**Comment by rrz5013** [comment]
I did do this.  Same error.

**Comment by dgant** [comment]
Can you confirm that BWEnv/include/libzmq/include/zmq.h is present?

Also I just realized this is the StarData revision of TorchCraft which predates my familiarity. CC @ebetica -- is there anything worth noting about that revision?

**Comment by rrz5013** [comment]
It took awhile, but I found the packages I needed to get it working. Thanks!
