### ISSUE TITLE
Throwing bad_alloc

### ISSUE THREAD

**Issue by rrz5013** [TorchCraft/TorchCraft#294]
Since now, I've only been able to run Torchcraft v1.3, but I would like to be able to use it without the need for Torch, since I'm only using Python and the replay parsing. I can see that v1.4 seems to work on doing this, but anytime I try to load a replay file in, I get a bad_alloc error on around line 216 of replayer.cpp:
in >> *this;
The replay files I read in are .tcr compressed files. I'm not sure if the data has changed between the different versions or why else I may be experiencing this issue.

**Comment by ebetica** [comment]
Are you using the StarData files? I just recently made another dump on torchcraft/develop, I can upload those if you need them.

**Comment by rrz5013** [comment]
Yeah, that would be great!

**Comment by ebetica** [comment]
I'm uploading it to s3://stardata/dumped_replays_tc1.4. It should be done uploading in 2 hours, and you can query to see if has the 20 `.tar.gz` files. Good luck!

Unfortunately, we had a big speed improvement but space regression, so the dumped replays are 2x bigger.
