### ISSUE TITLE
Install script fails on Mac

### ISSUE THREAD

**Issue by liboyue** [TorchCraft/TorchCraft#3]
In this file, https://github.com/TorchCraft/TorchCraft/blob/master/docs/user/bwapi_on_linux.md, clone command should be ```git clone https://github.com/TorchCraft/TorchCraft.git```

TorchCraft/quick_setup.sh fails on Mac.
Line 5, ```readlink -f``` does not work on Mac
Line 20, maybe it is ```cp -R```?
Line 22, ```sed -i "s|^ai *=.*|ai=$SC_DIR/BWEnv.dll|" bwapi-data/bwapi.ini``` should be ```sed -i '' "s|^ai *=.*|ai=$SC_DIR/BWEnv.dll|" bwapi-data/bwapi.ini```

And I can't run AIModule... Could you please take a look? Thanks :)

**Comment by spencerduncan** [comment]
>And I can't run AIModule

What happens when you try to run AIModule?

**Comment by ebetica** [comment]
OSX Is not a supported platform yet. If you can confirm these changes work on both OSX and Ubuntu, please submit a PR.

I recently added a note in https://github.com/TorchCraft/TorchCraft/tree/master/examples on appending '-t $ip' to the end of your commands so TorchCraft finds the right client to connect to.

**Comment by liboyue** [comment]
@spencerduncan 
```wine: Call from 0x7b827058 to unimplemented function msvcr120.dll.?_Id@_CurrentScheduler@details@Concurrency@@SAIXZ, aborting```
It turns out I should run ```winecfg``` and add msvcr120.dll. Thanks

**Comment by liboyue** [comment]
@ebetica I'll try

**Comment by spencerduncan** [comment]
liboyue:

Be sure to run `winetricks -q vcrun2013` if you haven't yet.
