### ISSUE TITLE
Overwrite config overwriting wrong things

### ISSUE THREAD

**Issue by ebetica** [TorchCraft/TorchCraft#34]
https://github.com/TorchCraft/TorchCraft/blob/develop/BWEnv/src/utils.cc#L132

If we overwrite "map", it will also take out "mapiteration" because "map" is a prefix of "mapiteration". Better to regex for `prefix + "\s*="` instead. Will make the change when I get around to it.

**Comment by jgehring** [comment]
@ebetica let's add this for the next release. Did you have a chance to fix this yet?

**Comment by ebetica** [comment]
Not yet, I also kind of want the frame diff in the next release too, I'll have that PR out pretty soon.
