### ISSUE TITLE
BWEnv.dll in error 404

### ISSUE THREAD

**Issue by tangzk** [TorchCraft/TorchCraft#5]
The file BWEnv.dll is in error 404, so do all files in [releases] directory. https://github.com/TorchCraft/TorchCraft/releases/download/v1.0/BWEnv.dll

**Comment by spencerduncan** [comment]
You can find those files in this release: https://github.com/TorchCraft/TorchCraft/releases/download/v1.0-0/torchcraft-v1.0-0.zip
