### ISSUE TITLE
custom_launcher unused

### ISSUE THREAD

**Issue by Meriipu** [TorchCraft/TorchCraft#68]
custom_launcher seems to be unused, but torchcraft.ini indicates nothing of the sort. 

What does the --headful bwheadless parameter do?
It seems to be appended to the launch command when setting launcher to bwheadless in torchcraft.ini, and to me --headful seems to not run in headless after all.

**Comment by ebetica** [comment]
You're right, this is unimplemented still: https://github.com/TorchCraft/TorchCraft/blob/master/BWEnv/src/controller.cc#L868

**Comment by Meriipu** [comment]
I tried to make a patch but there were some other differences I did not make so I am rather just posting my short changes here, since they might be made in a cleaner way anyways. 

Is there any reason they were not made originally considering they are pretty small?

utils.h:
```
void launchSCCustom(const std::wstring& sc_path_, 
  const std::wstring& command);
```


controller.cc
```
void Controller::launchStarCraft()
{
  if (config_->assume_on)
    return;

  if (config_->launcher == "bwheadless")
  {
    Utils::launchSCWithBWheadless(sc_path_, tc_path_);
  }
  else if (config_->launcher == "injectory")
  {
    Utils::launchSCWithInjectory(sc_path_, tc_path_);
  }
  else if (config_->launcher == "custom")
  {
	std::string custom_launcher = config_->custom_launcher;
	std::wstring command(custom_launcher.length(), L' ');
	std::copy(custom_launcher.begin(), custom_launcher.end(), command.begin());
	Utils::launchSCCustom(sc_path_, command);
  }
  else {
    // TODO decide what to do here
    // I'd rather the user failed with bad config, as opposed to
    // defaulting to bwheadless.
    throw std::exception();
  }
}
```

utils.cc
```
void Utils::launchSCCustom(const std::wstring& sc_path_, const std::wstring& command)
{
	std::cout << std::string(command.begin(), command.end()) << std::endl;
	starcraftInject(command, sc_path_, false);
}
```

**Comment by edran** [comment]
> Is there any reason they were not made originally considering they are pretty small?

We mostly didn't find the time to implement it and adequately test it  :) Feel free to submit a PR.

**Comment by ebetica** [comment]
Fixed in https://github.com/TorchCraft/TorchCraft/pull/74
