### ISSUE TITLE
launcher=bwheadless does not work as expected

### ISSUE THREAD

**Issue by Meriipu** [TorchCraft/TorchCraft#70]
From what I have understood, setting the launcher to bwheadless in torchcraft.ini results in the launch of this command:

```
bwheadless.exe --headful -e StarCraft.exe -l bwapi-data/BWAPI.dll
```

The first problem I have with this is the --headful parameter, which is hardcoded and seems to launch bwheadless in not headless mode.

The second problem might be me misunderstanding, but without the -h parameter (along with a -m mappath), bwheadless tries to join a game rather than host it. This means I have to run a second bwheadless instance to host the game as far as I understand. 

Much of this would be solved if custom_launcher actually launched the command #68 (and the documentation more explanatory)

I have been trying to solve it myself by patching but I can not get torchcraft to build.

**Comment by ebetica** [comment]
What is your environment? Are you using Windows or Linux + .dll or .exe?

**Comment by Meriipu** [comment]
StarCraft + TorchCraft server (that loads torchcraft.ini) running on Windows.

Client that loads the simple_exe.lua and connects to Windows server is running on Linux

I run BWEnv.exe on Windows

**Comment by ebetica** [comment]
I don't think we've actually have tested running bwheadless in headless mode. I'm not sure how well it works. Please let us know if you find out. We've also not really been using the .exe, instead preferring the .dll, since we cannot launch multiple instances of starcraft with the .exe.

Try using bwapi.ini to control how bwapi behaves.

**Comment by Meriipu** [comment]
To run it in headless I need to be able to change the launch parameter, though. 
And for now I have to build it myself to do that, and I have huge issues getting it to build.

I have not had much luck getting bwapi.ini to do anything I think

**Comment by ebetica** [comment]
Once you set up the BWAPI_DIR, I think your bwapi.ini might also begin working, I'm not sure.

**Comment by Meriipu** [comment]
I have tried launching it without --headful, and although the client seems to connect and the game gets hosted, nothing else happens as far as I can tell (it works with --headful, though is not headless on the server end)

launcher=custom
custom_launcher = C:\StarCraft\bwheadless.exe -e C:\StarCraft\StarCraft.exe -l C:\StarCraft\bwapi-data\BWAPI.dll -h -m maps/BroodWar/m5v5_c_far.scm -r Terran --installpath C:\StarCraft\

I ran simple_exe.lua with all but the 5v5 marines map removed from the maps list, and with initial_map set to maps[1]. No other output appears either on client side or server side after "Connection successful\nConnected to a StarCraft client" on the server side

I have no idea whether TorchCraft (on the windows server side) expects something from bwheadless maybe

**Comment by edran** [comment]
Two things:
1. It's somewhat unclear whether you are trying to launch TorchCraft `dll` or `exe`. If you are trying to do the former, you need to link to `BWEnv.dll` too, while if you are doing the latter you just need to run `BWEnv.exe`.
2. As @ebetica said, `BWEnv.exe` is slower and doesn't allow to run multiple instances of the server yet, so I suggest starting with the `dll` version.

**Comment by Meriipu** [comment]
Going to try dll then. Thanks.

**Comment by ebetica** [comment]
Fixed in https://github.com/TorchCraft/TorchCraft/pull/74 , feel free to start another issue if something else is block you @Meriipu.
