### ISSUE TITLE
Improve release packaging

### ISSUE THREAD

**Issue by Mistobaan** [TorchCraft/TorchCraft#80]
- Add to the zip release the configuration files under `./config`
- Add the maps under `./maps`

Update the instructions in the website

**Comment by ebetica** [comment]
I added the config and maps in the new minor release + some bugfixes. If you get the chance, can you change the instructions where you think would be helpful and submit a PR? Thanks!

**Comment by edran** [comment]
I have updated the instructions on the wiki, and we now have `TorchCraft/tc-prepare-release`.

Closing.
