### ISSUE TITLE
TorchCraft Client doesn't compile in Visual C++

### ISSUE THREAD

**Issue by ratiotile** [TorchCraft/TorchCraft#83]
**Background**
The TorchCraft Client was designed to run in linux.
https://github.com/TorchCraft/TorchCraft/blob/master/examples/cpp/simple_dll.cpp is an example of a client implementation in pure c++.

**Problem**
All versions of Visual Studio have a max of 127 macro arguments. The C++ standard says that compilers should support 256 parameters for functions. TorchCraft's use of Better Enums has 258 parameters.

Trying to build enum_macros.h throws this msvc error:
`torchcraft\include\enum_macros.h(553): fatal error C1112: compiler limit: '258' too many macro arguments, only '127' allowed`

Minimum code to reproduce:
```
#include "TorchCraft\include\client.h"
```

Googling for workarounds for msvc turned up this answer.
> No. There is no way around the internal compiler limit.
> The only thing you can do is to split your macro into 2 macros.

**Proposal**
Identify where Better Enums is used throughout the code, and figure out if it can be replaced, for example with constexpr.

**Comment by ebetica** [comment]
Try VS2013. The project is not set up for VS2015.

**Comment by ratiotile** [comment]
The compiler limits aren't any different for VS2013

https://msdn.microsoft.com/en-us/library/ft39hh4x(v=vs.120).aspx

**Comment by edran** [comment]
Hi @ratiotile - the point is that neither us nor BWAPI are currently supporting VS2013. This will change at some point in the future, but we are currently focusing on other things at the moment. If you manage to set it up, please feel free to open a pull request :)

**Comment by vkhalidov** [comment]
Frankly speaking, "better enums" for int data is a little bit an overkill. You can redefine the macro to use traditional enums in case of Windows.

**Comment by jgehring** [comment]
The main reason to use "better enums" is to make these enums easily accessible to scripting languages where look-up is done by name. This would be pretty painful otherwise. It seems that constexpr support in VS is not optimal either. Can you use clang or gcc/mingw to compile the client?
