### ISSUE TITLE
torchcraft installation problem:missing dependencies for torchcraft

### ISSUE THREAD

**Issue by wweichn** [TorchCraft/TorchCraft#97]
when I run the command sudo luarocksmake *.rockspec in Ubuntu 16.04, it showed

Missing dependencies for torchcraft:
torch >= 7.0
lua-cjson 
penlight 

 

Error: Could not satisfy dependency: torch >= 7.0

ps:I have already installed torch 7.0 and it can run correctly.

**Comment by edran** [comment]
Hi @starryskyWW, can you give us some more info?

* Where is your distro installed?
* What is the output of `which luarocks`?
* Can you run `th` from your shell?

**Comment by starryskyWW** [comment]
The installation directory is ~/TorchCraft for TorchCraft, and ~/torch for torch. 
The output is ~/torch/install/bin/luarocks.
I can run `th`  from my shell ,and it shows correctly.
BTW, after I deleted the dependencies check in the **torchcraft-1.2-1.rockspec** in TorchCraft, I mean the words inside "{}" `(dedependencies  = {
torch >= 7.0
lua-cjson
penlight }` 
the original mistake disappeared, and there is a new mistake showed that 
  

> CMake

> Error at CMakeLists.txt:8 (FIND_PACKAGE):
  By not providing "FindTorch.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Torch", but
  CMake did not find one.

>  Could not find a package configuration file provided by "Torch" with any of
  the following names:

    TorchConfig.cmake
    torch-config.cmake

>  Add the installation prefix of "Torch" to CMAKE_PREFIX_PATH or set
  "Torch_DIR" to a directory containing one of the above files.  If "Torch"
  provides a separate development package or SDK, be sure it has been
  installed.


> -- Configuring incomplete, errors occurred!
See also "/home/ww/TorchCraft/build/CMakeFiles/CMakeOutput.log".

I dont know what caused the situation. Thanks so much.

**Comment by jgehring** [comment]
> The installation directory is ~/TorchCraft for TorchCraft, and ~/torch for torch.

Are you saying that you want to install TorchCraft in another directory than your torch installation? What happens if you try to install it without sudo? You should not need elevated privileges for the installation if your torch installation is in your homedir (if you did not install torch with sudo). How did you install torch? Do you have something like `. $HOME/torch/install/bin/torch-activate` in your .bashrc?

**Comment by starryskyWW** [comment]
no,both torch and torchcraft are installed under the directory /home/ww.
Do you mean that I should install torchcraft inside torch?When I ran luarocksmake without sudo, it showed I have no permission.
Yeah, I have it. but it doesn't have any effect even if I ran the torch_activate.

**Comment by jgehring** [comment]
Hm, the permission error is weird. By default, `luarocks make` should install the package into ~/torch/install. If you don't have write permissions for that directory, something did go wrong at some point. Are you able to install other torch-related packages, e.g. `luarocks install torchnet`?

**Comment by edran** [comment]
@wweichn do you have any updates on this?

**Comment by wweichn** [comment]
I use torchcraft-py instead, and it works fine

**Comment by edran** [comment]
Alright, so I'll close this issue. 

FYI we provide a native python interface now: https://github.com/TorchCraft/TorchCraft/tree/master/py

**Comment by TaehwanKwon** [comment]
@edran 
Do you mean that I don't need to install lua and torch 7.0 to use torchcraft with python??

**Comment by edran** [comment]
@TaehwanKwon Correct.

However, please, don't spam other closed issues, as you are notifying everybody in the thread. Thanks.
